name: umps_iso_1972
description: Photo Judging Interface for Upper Myanmar Photographic Society

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  get: ^4.6.1
  intl: ^0.17.0
  objectbox: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.10

  objectbox_generator:
    git:
      url: https://github.com/sawthiha/objectbox-dart.git
      ref: custom-output
      path: generator

  flutter_lints: ^1.0.0

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/

# objectbox:
#   code_file: objectbox.code.dart